### ISSUE TITLE
Breakage in 2.9.0:  Error: Cannot find module '../src/cli/run'

### ISSUE THREAD

**Issue by jacekkopecky** [qunitjs/qunit#1367]
## Tell us about your runtime:

* **QUnit version**: 2.9.0
* **What environment are you running QUnit in? (e.g., browser, Node)**: Node (10.11.0)
* **How are you running QUnit? (e.g., script, testem, Grunt)**: `./node_modules/.bin/qunit test.js`

## What are you trying to do?

Run tests that worked under 2.8.0. 

Code that reproduces the problem: an empty `test.js`

## What did you expect to happen?

Global failure, no tests to run.

## What actually happened?

```
Error: Cannot find module '../src/cli/run'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/jacekkopecky/wscwk2/node_modules/qunit/bin/qunit.js:6:13)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
```

**Comment by rwjblue** [comment]
@Krinkle - https://github.com/qunitjs/qunit/pull/1344 introduced this issue (and 2.9.0 is _roughly_ completely borked due to it). The `files` listing in `package.json` does not include `src` at all and so they are not included in the final published tarball.

**Comment by rwjblue** [comment]
I submitted https://github.com/qunitjs/qunit/pull/1368 to fix (and help prevent this regression in the future).

**Comment by trentmwillis** [comment]
So sorry about this! @rwjblue thanks for the PR to fix. Will review and get out a new version ASAP.

**Comment by trentmwillis** [comment]
Re-opening until a new version is released...

**Comment by trentmwillis** [comment]
Okay, 2.9.1 has been released and should fix this issue. Again, apologies for the inconvenience!

**Comment by jacekkopecky** [comment]
Thank you! If you ever do decide to integrate that in CI and remember this conversation, please post here so I know – I'm a lecturer in software engineering and there's an excellent lesson for us in here.
