### ISSUE TITLE
--require @babel/register does not seem to work

### ISSUE THREAD

**Issue by NullVoxPopuli** [qunitjs/qunit#1414]
## Tell us about your runtime:

* **QUnit version**: 2.9.3
* **What environment are you running QUnit in? (e.g., browser, Node)**: Node
* **How are you running QUnit? (e.g., script, testem, Grunt)**: `yarn qunit ...`

I'm using Node 12.13.0

## What are you trying to do?

Run tests written in TypeScript via:

```
yarn qunit --require @babel/register tests/**/*-test.ts
```

Code that reproduces the problem: https://github.com/NullVoxPopuli/qunit-assertions-extra/pull/4

babel.config.js:
```js
'use strict';

module.exports = {
  presets: [require('@babel/preset-env'), require('@babel/preset-typescript')],
  plugins: [
    require('@babel/plugin-proposal-class-properties'),
    require('@babel/plugin-proposal-object-rest-spread'),
  ],
};
```

I noticed that when compiling with rollup, I needed to specify additional things, but I don't think I'm to the point where module resolution affects tests yet. I have syntax issues -- which tells me that babel isn't running . :(

## What did you expect to happen?

Tests to run.

## What actually happened?

Qunit takes about 40s to start, and then gives this error:
```
not ok 1 tests/unit/contains-test.ts > Failed to load the test file with error:
/home/lprestonsegoiii/Development/NullVoxPopuli/qunit-assertions-extra/tests/unit/contains-test.ts:1
import { module, test } from 'qunit';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at Module._compile (internal/modules/cjs/loader.js:892:18)
    at Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Object.newLoader [as .js] (/home/lprestonsegoiii/Development/NullVoxPopuli/qunit-assertions-extra/node_modules/pirates/lib/index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at run (/home/lprestonsegoiii/Development/NullVoxPopuli/qunit-assertions-extra/node_modules/qunit/src/cli/run.js:55:4)
    at Object.<anonymous> (/home/lprestonsegoiii/Development/NullVoxPopuli/qunit-assertions-extra/node_modules/qunit/bin/qunit.js:56:2)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
  ---
  message: "should be able to load file"
  severity: failed
  actual: false
  expected: true
  stack:     at Object.<anonymous> (/home/lprestonsegoiii/Development/NullVoxPopuli/qunit-assertions-extra/node_modules/qunit/src/cli/run.js:62:13)

```

**Comment by Krinkle** [comment]
Based on the error, I think this might be a configuration issue with Babel in terms of module vs script context.

@NullVoxPopuli I created an isolated example with plain a TypeScript module and `--require`, which works at <https://gist.github.com/Krinkle/44f71cd8c40cc9072d061a8a512345d0>.

I'm hoping this helps you narrow down the issue. If not, could you fork this gist and add Babel to the mix in a way that re-creates the issue?

**Comment by Krinkle** [comment]
🤖  _Closing inactive support issue. If it is not solved, mention more details and we'll re-open it. You can also [chat with us](https://gitter.im/qunitjs/qunit)!_
