### ISSUE TITLE
On Node 10 and older, CLI can't find "qunit" if there's a "qunit.json" file

### ISSUE THREAD

**Issue by Krinkle** [qunitjs/qunit#1484]
## Tell us about your runtime:

* **QUnit version**: 2.11.2
* **What environment are you running QUnit in? (e.g., browser, Node)**: Node

## What are you trying to do?

Running `qunit test/foo.js` via `npm test` from package.json.

The project directory is a clone of <https://github.com/wikimedia/eslint-config-wikimedia/>.

## What actually happened?

The QUnit CLI process fails early on due to confusing this file for the qunit package:

```
/eslint-config-wikimedia/node_modules/js-reporters/dist/js-reporters.js:1530
    runner.on('runStart', this.onRunStart.bind(this));
           ^

TypeError: runner.on is not a function
    at new TapReporter (/eslint-config-wikimedia/node_modules/js-reporters/dist/js-reporters.js:1530:12)
    at Function.init (/eslint-config-wikimedia/node_modules/js-reporters/dist/js-reporters.js:1598:14)
    at run (/eslint-config-wikimedia/node_modules/qunit/src/cli/run.js:45:19)
    at Object.<anonymous> (/eslint-config-wikimedia/node_modules/qunit/bin/qunit.js:56:2)
```

Manual inspection reveals that the `runner` variable received from https://github.com/qunitjs/qunit/blob/2.11.2/src/cli/require-qunit.js#L7 is in fact the `qunit.json` file, and not the `qunit` package.
```js
		const localQUnitPath = resolve( "qunit", { paths: [ process.cwd() ] } );
```

**Comment by Krinkle** [comment]
I raised this upstream with Node because it seems to me like a bug.

* Calling `require('qunit')` directly from that same working directory does not return `./qunit.json`. It only happens when using the `paths` option.
* It only fails on Node 10. It works fine on Node 14.

See https://github.com/nodejs/node/issues/35367

**Comment by Krinkle** [comment]
Suggested workaround for now, until we drop Node 10 support:

```js
require.resolve( "qunit", { paths: [ process.cwd() + '/node_modules', process.cwd() ] } )
```

**Comment by Krinkle** [comment]
Suggested workaround for now, until we drop Node 10 support:

```js
> process.versions.node
10.15.2

> require.resolve( "qunit", { paths: [ process.cwd() ] } )
'/eslint-config-wikimedia/qunit.json'

> require.resolve( "qunit", { paths: [ process.cwd() + '/node_modules', process.cwd() ] } )
'/eslint-config-wikimedia/node_modules/qunit/qunit/qunit.js'
```
